spring:
  application:
    name: netflix-zuul-api-gateway-server
server:
  port: 8765
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    users:
      path: /cts/superstore/**
      serviceId: get-customer-id-service
#  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
endpoints:
  routes:
    sensitive: false